--************************************************************************--
--** ORGMModData
--**
--************************************************************************--
ORGMRModData = ISReloadUtil:derive("ORGMModData");

--** 9mm

local Box9mm = { type = "Box9mm",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'AmmolistSmP',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 50,
	reloadTime = 5,
	rackTime = 0};
	
local Box9mmHP = { type = "Box9mmHP",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'AmmolistSmP',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 50,
	reloadTime = 5,
	rackTime = 0};
	
local Ber92 = { type = "Ber92",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	magType = 'MaglistBeretta',
	clipName = 'Beretta 92/93 magazines',
	clipIcon = 'Ber92Mag',
	shootSound = '9mmFire',
	clickSound = 'ORGMSmallPistolEmpty',
	ejectSound = 'ORGMSmallPistolOut',
	insertSound = 'ORGMSmallPistolIn',
	rackSound = 'ORGMSmallPistolRack',
	loadStyle = 'magfed',
	containsMag = 0,
	magInserted = nil,
	reloadTime = 10,
	rackTime = 10,
	clipData = Ber92Mag };

local BerMag10 = { type = "BerMag10",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 10,
	reloadTime = 30,
	rackTime = 10};
	
local BerMag15 = { type = "BerMag15",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 15,
	reloadTime = 30,
	rackTime = 10};
	
local BerMag17 = { type = "BerMag17",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 17,
	reloadTime = 30,
	rackTime = 10};
	
local BerMag20 = { type = "BerMag20",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 20,
	reloadTime = 30,
	rackTime = 10};
	
local BerMag30 = { type = "BerMag30",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 30,
	reloadTime = 30,
	rackTime = 10};
	
local BerMag32 = { type = "BerMag32",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 32,
	reloadTime = 30,
	rackTime = 10};

local BrownHPMag10 = { type = "BrownHPMag10",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 10,
	reloadTime = 30,
	rackTime = 10};

local BrownHPMag13 = { type = "BrownHPMag13",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 13,
	reloadTime = 30,
	rackTime = 10};

local BrownHPMag15 = { type = "BrownHPMag15",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 15,
	reloadTime = 30,
	rackTime = 10};

local Glock9mmMag6 = { type = "Glock9mmMag6",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 6,
	reloadTime = 30,
	rackTime = 10};

local Glock9mmMag10comp = { type = "Glock9mmMag10comp",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 10,
	reloadTime = 30,
	rackTime = 10};

local Glock9mmMag10full = { type = "Glock9mmMag10full",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 10,
	reloadTime = 30,
	rackTime = 10};

local Glock9mmMag10scomp = { type = "Glock9mmMag10scomp",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 10,
	reloadTime = 30,
	rackTime = 10};

local Glock9mmMag12 = { type = "Glock9mmMag12",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 12,
	reloadTime = 30,
	rackTime = 10};

local Glock9mmMag15 = { type = "Glock9mmMag15",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 15,
	reloadTime = 30,
	rackTime = 10};

local Glock9mmMag17 = { type = "Glock9mmMag17",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 17,
	reloadTime = 30,
	rackTime = 10};

local Glock9mmMag19 = { type = "Glock9mmMag19",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 19,
	reloadTime = 30,
	rackTime = 10};

local Glock9mmMag31 = { type = "Glock9mmMag31",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 31,
	reloadTime = 30,
	rackTime = 10};

local Glock9mmMag33 = { type = "Glock9mmMag33",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 33,
	reloadTime = 30,
	rackTime = 10};

local Glock9mmMag50 = { type = "Glock9mmMag50",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 50,
	reloadTime = 30,
	rackTime = 10};

local M19119mmMag8 = { type = "M19119mmMag8",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 8,
	reloadTime = 30,
	rackTime = 10};

local HKMP5Mag10 = { type = "HKMP5Mag10",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 10,
	reloadTime = 30,
	rackTime = 10};

local HKMP5Mag15 = { type = "HKMP5Mag15",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 15,
	reloadTime = 30,
	rackTime = 10};

local HKMP5Mag20 = { type = "HKMP5Mag20",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 20,
	reloadTime = 30,
	rackTime = 10};

local HKMP5Mag30 = { type = "HKMP5Mag30",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 30,
	reloadTime = 30,
	rackTime = 10};

local HKMP5Mag40 = { type = "HKMP5Mag40",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 40,
	reloadTime = 30,
	rackTime = 10};

local HKMP5Mag50 = { type = "HKMP5Mag50",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 50,
	reloadTime = 30,
	rackTime = 10};

local HKMP5Mag100 = { type = "HKMP5Mag100",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 100,
	reloadTime = 30,
	rackTime = 10};

local HKP7Mag13 = { type = "HKP7Mag13",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 13,
	reloadTime = 30,
	rackTime = 10};
	
local KelTecP11Mag10 = { type = "KelTecP11Mag10",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 10,
	reloadTime = 30,
	rackTime = 10};

local M19119mmMag8 = { type = "M19119mmMag8",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 8,
	reloadTime = 30,
	rackTime = 10};

local M19119mmMag9off = { type = "M19119mmMag9off",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 9,
	reloadTime = 30,
	rackTime = 10};

local M19119mmMag9std = { type = "M19119mmMag9std",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 9,
	reloadTime = 30,
	rackTime = 10};

local M19119mmMag10 = { type = "M19119mmMag10",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 10,
	reloadTime = 30,
	rackTime = 10};

local RugerP9mmmMag10 = { type = "RugerP9mmmMag10",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 10,
	reloadTime = 30,
	rackTime = 10};

local RugerP9mmmMag15 = { type = "RugerP9mmmMag15",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 15,
	reloadTime = 30,
	rackTime = 10};

local RugerP9mmmMag17 = { type = "RugerP9mmmMag17",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 17,
	reloadTime = 30,
	rackTime = 10};

local RugerP9mmmMag20 = { type = "RugerP9mmmMag20",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 20,
	reloadTime = 30,
	rackTime = 10};

local RugerP9mmmMag32 = { type = "RugerP9mmmMag32",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 32,
	reloadTime = 30,
	rackTime = 10};

local RugerSR9Mag10 = { type = "RugerSR9Mag10",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 10,
	reloadTime = 30,
	rackTime = 10};

local RugerSR9Mag10comp = { type = "RugerSR9Mag10comp",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 10,
	reloadTime = 30,
	rackTime = 10};

local RugerSR9Mag17 = { type = "RugerSR9Mag17",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 17,
	reloadTime = 30,
	rackTime = 10};
	
local SmP50RndBox = { type = "SmP50RndBox",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'AmmolistSmP',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 50,
	reloadTime = 5,
	rackTime = 0};
	
local SmP100RndBox = { type = "SmP100RndBox",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'AmmolistSmP',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapacity = 100,
	reloadTime = 5,
	rackTime = 0};

local SW5906Mag10 = { type = "S&W5906Mag10",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 10,
	reloadTime = 30,
	rackTime = 10};

local SW5906Mag15 = { type = "S&W5906Mag15",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 15,
	reloadTime = 30,
	rackTime = 10};

local SW5906Mag17 = { type = "S&W5906Mag17",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 17,
	reloadTime = 30,
	rackTime = 10};

local SW5906Mag20 = { type = "S&W5906Mag20",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 20,
	reloadTime = 30,
	rackTime = 10};

local SWMP9Mag7shield = { type = "S&WMP9Mag7shield",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 7,
	reloadTime = 30,
	rackTime = 10};

local SWMP9Mag8shield = { type = "S&WMP9Mag8shield",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 8,
	reloadTime = 30,
	rackTime = 10};

local SWMP9Mag10 = { type = "S&WMP9Mag10",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 10,
	reloadTime = 30,
	rackTime = 10};

local SWMP9Mag10comp = { type = "S&WMP9Mag10comp",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 10,
	reloadTime = 30,
	rackTime = 10};

local SWMP9Mag12comp = { type = "S&WMP9Mag12comp",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 12,
	reloadTime = 30,
	rackTime = 10};

local SWMP9Mag15 = { type = "S&WMP9Mag15",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 15,
	reloadTime = 30,
	rackTime = 10};

local SWMP9Mag17 = { type = "S&WMP9Mag17",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 17,
	reloadTime = 30,
	rackTime = 10};

local TaurusPT111Mag10 = { type = "TaurusPT111Mag10",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 10,
	reloadTime = 30,
	rackTime = 10};

local TaurusPT111Mag12 = { type = "TaurusPT111Mag12",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 12,
	reloadTime = 30,
	rackTime = 10};

local Tec9Mag20 = { type = "Tec9Mag20",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 20,
	reloadTime = 30,
	rackTime = 10};

local Tec9Mag32 = { type = "Tec9Mag32",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 32,
	reloadTime = 30,
	rackTime = 10};

local Tec9Mag50 = { type = "Tec9Mag50",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 50,
	reloadTime = 30,
	rackTime = 10};

local UziMag20 = { type = "UziMag20",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 20,
	reloadTime = 30,
	rackTime = 10};

local UziMag25 = { type = "UziMag25",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 25,
	reloadTime = 30,
	rackTime = 10};

local UziMag32 = { type = "UziMag32",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 32,
	reloadTime = 30,
	rackTime = 10};

local UziMag40 = { type = "UziMag40",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 40,
	reloadTime = 30,
	rackTime = 10};

local UziMag50 = { type = "UziMag50",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist9mm',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 50,
	reloadTime = 30,
	rackTime = 10};
	
--**4570
	local Box4570 = { type = "Box4570",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist4570',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 50,
	reloadTime = 30,
	rackTime = 10};
	
	local Box4570HP = { type = "Box4570HP",
	moduleName = 'ORGM',
	reloadClass = 'ORGMLoadClass',
	ammoType = 'Ammolist4570',
	loadStyle = 'internal',
	shootSound = 'none',
	clickSound = nil,
	ejectSound = 'ORGMMagLoad',
	insertSound = 'ORGMMagLoad',
	rackSound = 'ORGMMagLoad',
	containsClip = 0,
	maxCapaity = 50,
	reloadTime = 30,
	rackTime = 10};

--************************************************************************--
--** ReloadUtil
--**
--************************************************************************--

ORGMLoadUtil:addLoadableType(Box9mm)
ORGMLoadUtil:addLoadableType(Box9mmHP)
ORGMLoadUtil:addLoadableType(Ber92)
ORGMLoadUtil:addLoadableType(BerMag10)
ORGMLoadUtil:addLoadableType(BerMag15)
ORGMLoadUtil:addLoadableType(BerMag17)
ORGMLoadUtil:addLoadableType(BerMag20)
ORGMLoadUtil:addLoadableType(BerMag30)
ORGMLoadUtil:addLoadableType(BerMag32)
ORGMLoadUtil:addLoadableType(BrownHPMag10)
ORGMLoadUtil:addLoadableType(BrownHPMag13)
ORGMLoadUtil:addLoadableType(BrownHPMag15)
ORGMLoadUtil:addLoadableType(Glock9mmMag6)
ORGMLoadUtil:addLoadableType(Glock9mmMag10comp)
ORGMLoadUtil:addLoadableType(Glock9mmMag10full)
ORGMLoadUtil:addLoadableType(Glock9mmMag10scomp)
ORGMLoadUtil:addLoadableType(Glock9mmMag12)
ORGMLoadUtil:addLoadableType(Glock9mmMag15)
ORGMLoadUtil:addLoadableType(Glock9mmMag17)
ORGMLoadUtil:addLoadableType(Glock9mmMag19)
ORGMLoadUtil:addLoadableType(Glock9mmMag31)
ORGMLoadUtil:addLoadableType(Glock9mmMag33)
ORGMLoadUtil:addLoadableType(Glock9mmMag50)
ORGMLoadUtil:addLoadableType(HKMP5Mag10)
ORGMLoadUtil:addLoadableType(HKMP5Mag15)
ORGMLoadUtil:addLoadableType(HKMP5Mag20)
ORGMLoadUtil:addLoadableType(HKMP5Mag30)
ORGMLoadUtil:addLoadableType(HKMP5Mag40)
ORGMLoadUtil:addLoadableType(HKMP5Mag50)
ORGMLoadUtil:addLoadableType(HKMP5Mag100)
ORGMLoadUtil:addLoadableType(HKP7Mag13)
ORGMLoadUtil:addLoadableType(KelTecP11Mag10)
ORGMLoadUtil:addLoadableType(M19119mmMag8)
ORGMLoadUtil:addLoadableType(M19119mmMag9off)
ORGMLoadUtil:addLoadableType(M19119mmMag9std)
ORGMLoadUtil:addLoadableType(M19119mmMag10)
ORGMLoadUtil:addLoadableType(RugerP9mmMag10)
ORGMLoadUtil:addLoadableType(RugerP9mmMag15)
ORGMLoadUtil:addLoadableType(RugerP9mmMag17)
ORGMLoadUtil:addLoadableType(RugerP9mmMag20)
ORGMLoadUtil:addLoadableType(RugerP9mmMag32)
ORGMLoadUtil:addLoadableType(RugerSR9Mag10)
ORGMLoadUtil:addLoadableType(RugerSR9Mag10comp)
ORGMLoadUtil:addLoadableType(RugerSR9Mag17)
ORGMLoadUtil:addLoadableType(SmP50RndBox)
ORGMLoadUtil:addLoadableType(SmP100RndBox)
ORGMLoadUtil:addLoadableType(SW5906Mag10)
ORGMLoadUtil:addLoadableType(SW5906Mag15)
ORGMLoadUtil:addLoadableType(SW5906Mag17)
ORGMLoadUtil:addLoadableType(SW5906Mag20)
ORGMLoadUtil:addLoadableType(SWMP9Mag7shield)
ORGMLoadUtil:addLoadableType(SWMP9Mag8shield)
ORGMLoadUtil:addLoadableType(SWMP9Mag10)
ORGMLoadUtil:addLoadableType(SWMP9Mag10comp)
ORGMLoadUtil:addLoadableType(SWMP9Mag12comp)
ORGMLoadUtil:addLoadableType(SWMP9Mag15)
ORGMLoadUtil:addLoadableType(SWMP9Mag17)
ORGMLoadUtil:addLoadableType(TaurusPT111Mag10)
ORGMLoadUtil:addLoadableType(TaurusPT111Mag12)
ORGMLoadUtil:addLoadableType(Tec9Mag20)
ORGMLoadUtil:addLoadableType(Tec9Mag32)
ORGMLoadUtil:addLoadableType(Tec9Mag50)
ORGMLoadUtil:addLoadableType(UziMag20)
ORGMLoadUtil:addLoadableType(UziMag25)
ORGMLoadUtil:addLoadableType(UziMag32)
ORGMLoadUtil:addLoadableType(UziMag40)
ORGMLoadUtil:addLoadableType(UziMag50)
ORGMLoadUtil:addLoadableType(Box4570)
ORGMLoadUtil:addLoadableType(Box4570HP)